name: Pull Request To Main
run-name: Run All Tests

on:
  pull_request:
    branches:
      - 'main'

jobs:
   integration_testing:
    needs: unit_testing
    runs-on: self-hosted
    container: python:3.12.3-slim